---  # yaml document beginning
# comment syntax

# data_folder: 
# puzzle_name: puzzle_0000005_RP_group_5
# exp_name: # used for comp, solver on alread precomputed data
verbosity: 2
# skip_done: True # for run_on_dataset


# repair --> number
# wikiart --> load_from_file
preprocessing:
  # piece_size: 251
  load_from_file: Yes
  piece_size: 0
  load_polygons: No



# extraction
features:
  lines:
    extracted: No
    detection_method: deeplsd
  motif:
    extracted: Yes
    detection_method: yolo-seg

compatibility:
  save_visualization: 
    enabled: No 
    cmap: RdYlGn
    img_format: jpg
    vmin: -1
    vmax: 1
    figsize: 100
    all_rotations: False
    save_every: 6
    save_RM: True
  grid: 
    xy_step: 9
    theta_step: 90
    xy_num_points: 31
    theta_num_points: 1
    canvas_buffer: 0  # if you need to ensure canvas is large enough - can be useful for special type of pieces
  # region matrix calculation
  regions:
    borders_dilation: 1
    borders_erosion: 1
    threshold_ovelrap_shapes: 
    # maybe here to distinguish RM features and CM features
    # features_list: [asda]
  # actual compatibility score calculation
  features:
    # all features SHOULD have 'enabled': Yes/No as it is checked internally from cmm.check_features_status()
    # and used to make the calculations
    shape: 
      enabled: No
      sigma: 1 # ?
      SDF_dilation: 75 # TODO: check if it should be different from borders dilstion!

      # this is used ONLY to save the pairwise alignment images where shape is actually "fitting", 
      # but the alignment is incorrect (use with caution, it needs GT!)
      # it is connected to the parameters in ['oracle']['pairwise_alignments_dataset']
      # so it should be enabled when also ['oracle']['create_pairwise_alignments_dataset'] is enabled!
      save_best_images: 
        enabled: No
        score_threshold: 0.8
        dist2GT_threshold: 15
        dist2hn_threshold: 15
        data_folder: '/run/user/1000/gvfs/sftp:host=gpu1.dsi.unive.it,user=luca.palmieri/home/ssd/datasets/RePAIR_ReLab_luca/PAD_v4/hard_negative'

    lines:
      enabled: No
      thr_coef: 0.13
      max_dist: 6 # could be changed during calculation (it is an upper bound)
      badmatch_penalty: 5 # again upper bound
      mismatch_penalty: 1 # repair
      k: 3
      cmp_cost: LAP
      # rmax: calculated 
      # border_tolerance: calculated
    motives: 
      enabled: No
      scoring_func: simple
      # simple scoring mechanism (touching pixels)
      simple_params: 
        dilation: 9
      # detection on aligned pairs of fragments (yolo based)
      detection_params:
        detector: yolo-seg
      # geometric (use lines/curves? BGU?)
      geometric_params:
        something: 1
    pairwise_alignment_discriminator:
      enabled: No
      trained_model_folder: ~pretrained_PADs/v4_fast_224/
      use_fast: True 
      use_batch: True 
      do_center_crop: True
      crop_height: 224
      crop_width: 224
      # method for computing the score:
      # 1. softmax (score is the score of output 1 (correct probability) after softmax)
      # 2. thresh (score is the score before softmax if it's above a threshold defined below)
      # 3. prob_diff (score is the difference between the two output `correct` and `wrong`)
      scoring_method: 'softmax' #'thresh', 'prob_diff'
      thresholds:
        positive: 2
        negative: 1.5
      cutoff_value: 0.05
      push_k_values: 3
      cutoff_value: 0.05
    alignment_scorer:
      enabled: No
      checkpoint_path: ~pretrained_AS/best.pth'
      threshold: 30
      radius: 30
      topK: 5
    alignments_ranker:
      enabled: Yes
      checkpoint_path: ~pretrained_AR/best.pth'
      threshold: 30
      radius: 30
      topK: 5
      split_method: 'fast' # or 'tournament'
      cutoff_value: 0.5 # set to zero all values below this
    oracle:
      enabled: No
      # this is for the creation of images for pairwise "good" and "bad" alignments
      create_pairwise_alignments_dataset: false
      pairwise_alignments_dataset:
        crop_images: True
        save_masks: True
        mask_type: 'pieces_center_first'
        padding: 5
        save_true_alignment: True 
        save_grid_alignment: True 
        save_wrong_alignments: True 
        wrong_alignments_num: 1
        # pairwise_alignments_dataset_folder: '/home/palma/Datasets/RePAIR_pairwise' #
        data_folder: '/run/user/1000/gvfs/sftp:host=gpu1.dsi.unive.it,user=luca.palmieri/home/ssd/datasets/RePAIR_ReLab_luca/PAD_v4'
    alignment_scorer:
      enabled: No
      checkpoint_path: ''
      threshold: 30
      radius: 30

aggregation:
  method: 'PAD'  

solver:
  T_first: 500 #1000
  T_next: 250 #500
  T_max: 1500 #3000
  PQ_mode: 'exp'
  no_rotations: False
  # TODO: switch to anchor ID
  anchor_index: 1 # TODO: null, None?
  max_adjacency_degree: 1
  # threshold
  accept_threshold: 0.75
  p_precision: 10
  grid:
    # ['gt','auto','manual', 'occ', 'neighbours_occ', 'extern', 'integration' 'integration_with_external']
    method: integration
    # this is used only when method is set to 'manual'
    manual_params:
      p_xy_size: [ 151,151 ]
      sandbox_size: [ 850, 850 ]   # size of sandbox_size in mm

    # integration with ReassembleNet
  reassembleNet:
    std_dev_x: 0.5
    std_dev_y: 0.5
    std_dev_t: 1
    sparsify_p: 0
    visualization: True
       
  # how to save the solution
  solution:
    save_pixel_solution: True 
    save_as_txt: True
    visualization:
      add_suffix: True
      in_the_suffix: 
        anchor_index: True 
        agg_method: True
        
    # if True, solution will be: 
    # name1 x1 y1 z1 p1
    # name2 x2 y2 z2 p2
    # if False
    # x1 y1 z1 p1
    # x2 y2 z2 p2
    include_names: True 

    # if False, will remove the probabilities p
    # and solution will be:
    # name1 x1 y1 z1
    # name2 x2 y2 z2
    include_probs: True
  
  # integration week parameters (to generate placement file)
  generate_placement_file: False
  placement:
    inflation_width: 20
    assembly_plan: spiral # snake
    save_plot: True


