---  # yaml document beginning
# comment syntax

# data_folder: 
# puzzle_name: puzzle_0000005_RP_group_5
# exp_name: # used for comp, solver on alread precomputed data
verbosity: 2
# skip_done: True # for run_on_dataset

preprocessing:
  piece_size: 251

# extraction
features:
  lines:
    extracted: No
    detection_method: deeplsd
  motif:
    extracted: Yes
    detection_method: yolo-seg

compatibility:
  save_visualization: 
    enabled: No 
    cmap: RdYlGn
    img_format: jpg
    vmin: -1
    vmax: 1
    figsize: 100
    all_rotations: False
    save_every: 6
  grid: 
    xy_step: 9
    theta_step: 90
    xy_num_points: 31
    theta_num_points: 1
  # region matrix calculation
  regions:
    borders_dilation: 1
    borders_erosion: 1
    threshold_ovelrap_shapes: 
    # maybe here to distinguish RM features and CM features
    # features_list: [asda]
  # actual compatibility score calculation
  features:
    # all features SHOULD have 'enabled': Yes/No as it is checked internally from cmm.check_features_status()
    # and used to make the calculations
    shape: 
      enabled: No
      sigma: 1 # ?
      SDF_dilation: 35 # TODO: check if it should be different from borders dilstion!
    lines:
      enabled: No
      thr_coef: 0.13
      max_dist: 6 # could be changed during calculation (it is an upper bound)
      badmatch_penalty: 5 # again upper bound
      mismatch_penalty: 1 # repair
      k: 3
      cmp_cost: LAP
      # rmax: calculated 
      # border_tolerance: calculated
    motives: 
      enabled: No
      scoring_func: simple
      # simple scoring mechanism (touching pixels)
      simple_params: 
        dilation: 9
      # detection on aligned pairs of fragments (yolo based)
      detection_params:
        detector: yolo-seg
      # geometric (use lines/curves? BGU?)
      geometric_params:
        something: 1
    pairwise_alignment_discriminator:
      enabled: Yes
      trained_model_folder: ~pretrained_PADs/v4_fast_224/
      use_fast: True 
      use_batch: True 
      do_center_crop: True
      crop_height: 224
      crop_width: 224
      use_thresh: False
      thresholds:
        positive: 2
        negative: 1.5
      cutoff_value: 0.05
      push_k_values: 3
    oracle:
      enabled: No
      # this is for the creation of images for pairwise "good" and "bad" alignments
      pairwise_alignments_dataset:
        enabled: No
        data_folder: ''
        padding: 5
        crop_images: True
          
aggregation:
  method: 'PAD'  

solver:
  T_first: 500 #1000
  T_next: 250 #500
  T_max: 1500 #3000
  PQ_mode: 'exp'
  no_rotations: False
  # TODO: switch to anchor ID
  anchor_index: 1 # TODO: null, None?
  max_adjacency_degree: 1
  # threshold
  accept_threshold: 0.75
  p_precision: 10
  grid:
    # ['gt','auto','manual', 'occ', 'neighbours_occ', 'extern', 'integration' 'integration_with_external']
    method: integration
    # this is used only when method is set to 'manual'
    manual_params:
      p_xy_size: [ 151,151 ]
      sandbox_size: [ 850, 850 ]   # size of sandbox_size in mm

  # integration with ReassembleNet
  reassembleNet:
    std_dev_x: 110
    std_dev_y: 110
    std_dev_t: 1 
       
  # how to save the solution
  solution:
    save_pixel_solution: True 
    save_as_txt: True
    visualization:
      add_suffix: True
      in_the_suffix: 
        anchor_index: True 
        agg_method: True
        
    # if True, solution will be: 
    # name1 x1 y1 z1 p1
    # name2 x2 y2 z2 p2
    # if False
    # x1 y1 z1 p1
    # x2 y2 z2 p2
    include_names: True 

    # if False, will remove the probabilities p
    # and solution will be:
    # name1 x1 y1 z1
    # name2 x2 y2 z2
    include_probs: True
  
  # integration week parameters (to generate placement file)
  generate_placement_file: False
  placement:
    inflation_width: 20
    assembly_plan: spiral # snake
    save_plot: True


